version: "3"

services:
  ftp-server:
    build:
      context: .
      dockerfile: Dockerfile-ftp/Dockerfile
    volumes:
      - ./ftproot:/ftproot
    network_mode: "host"
    restart: unless-stopped

  php-container:
    build:
      context: .
      dockerfile: Dockerfile-php/Dockerfile
    volumes:
      - ./ftproot:/ftproot
      - ./projects:/projects
      - ./template:/template
    ports:
      - "80:80"
    restart: unless-stopped
